services:
  db:
    image: postgres:16-alpine
    container_name: message-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka: 
    image: apache/kafka:3.7.2
    container_name: message-service-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "29092:29092"
    volumes:
      - kafkadata:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka-init:
    image: apache/kafka:3.7.2
    container_name: message-service-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: 
      - /bin/bash
      - -c
      - |
        /opt/kafka/bin/kafka-topics.sh \
        --create \
        --if-not-exists \
        --topic message.in \
        --partitions 3 \
        --replication-factor 1
    restart: "no"
    # В проде replication-factor > 1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - kafkadata:/var/lib/kafka/data
  
volumes:
  pgdata:
  kafkadata:

